
import { Patient, InventoryItem, EndoscopyRecord, IncidentRecord } from '../types';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ReportMetadata {
  generatedBy: string;
  filters: string;
  period?: string;
}

const calculateLOSValue = (admissionDate: string) => {
  const start = new Date(admissionDate);
  const today = new Date();
  start.setHours(0, 0, 0, 0);
  today.setHours(0, 0, 0, 0);
  const diffTime = today.getTime() - start.getTime();
  const diffDays = Math.max(0, Math.floor(diffTime / (1000 * 60 * 60 * 24)));
  return diffDays;
};

export const exportToPDF = (title: string, headers: string[], rows: any[][], metadata: ReportMetadata) => {
  const doc = new jsPDF('landscape'); 
  
  doc.setFontSize(22);
  doc.setTextColor(220, 38, 38); 
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("Clinical Management System", 14, 26);

  doc.setDrawColor(226, 232, 240); 
  doc.line(14, 32, 282, 32);

  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59); 
  doc.text(title, 14, 42);

  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105); 
  doc.text(`Generated By: ${metadata.generatedBy}`, 14, 50);
  doc.text(`Timestamp: ${new Date().toLocaleString()}`, 14, 55);
  doc.text(`Active Filters: ${metadata.filters}`, 14, 60);
  if (metadata.period) {
    doc.text(`Report Period: ${metadata.period}`, 14, 65);
  }

  const tableStartY = metadata.period ? 75 : 70;

  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: tableStartY,
    styles: { fontSize: 7, font: 'helvetica', cellPadding: 2, overflow: 'linebreak' },
    headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255], fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { top: 20 },
    didDrawPage: function (data: any) {
      const str = "Page " + (doc as any).internal.getNumberOfPages();
      doc.setFontSize(8);
      const pageSize = doc.internal.pageSize;
      const pageHeight = pageSize.height ? pageSize.height : (pageSize as any).getHeight();
      doc.setTextColor(148, 163, 184); 
      doc.text(str, data.settings.margin.left, pageHeight - 10);
      doc.text("Official HDU Internal Report - Unauthorized reproduction is strictly prohibited", 180, pageHeight - 10);
    }
  });

  doc.save(`${title.replace(/\s+/g, '_').toLowerCase()}_${new Date().getTime()}.pdf`);
};

export const exportAccessSlipPDF = (userData: { name: string; email: string; password?: string; role: string }) => {
  const doc = new jsPDF();
  
  // Header Box
  doc.setFillColor(15, 23, 42); // Slate-900
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text("HDU MANAGEMENT SYSTEM", 105, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text("STAFF ACCESS CREDENTIALS SLIP", 105, 30, { align: 'center' });

  // Border Around Content
  doc.setDrawColor(226, 232, 240);
  doc.rect(20, 50, 170, 100);

  // Body Content
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(12);
  
  const startX = 30;
  let currentY = 70;

  const addField = (label: string, value: string) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, startX, currentY);
    doc.setFont('helvetica', 'normal');
    doc.text(value, startX + 50, currentY);
    currentY += 15;
  };

  addField("Staff Name", userData.name.toUpperCase());
  addField("Email Address", userData.email);
  addField("Access Level", userData.role.toUpperCase());
  addField("Temp Password", userData.password || "******** (Previously Set)");

  // Footer Instructions
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const footerText = "Thank you for joining us! You can now use the portal to manage clinical records. Please change your password after your first login.";
  const splitText = doc.splitTextToSize(footerText, 150);
  doc.text(splitText, 105, 130, { align: 'center' });

  // System Metadata
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Issued On: ${new Date().toLocaleString()}`, 30, 145);
  doc.text("Internal Use Only - Confidential Clinical Tool", 105, 160, { align: 'center' });

  doc.save(`access_slip_${userData.name.toLowerCase().replace(/\s+/g, '_')}.pdf`);
};

export const exportPatientsPDF = (patients: Patient[], metadata: ReportMetadata) => {
  const headers = ['S.No', 'Reg No', 'Patient Name', 'Gender', 'Category', 'Code', 'Consultant', 'In-Date', 'Out-Date', 'LOS'];
  const rows = patients.map(p => [
    p.serialNo, 
    p.regNo, 
    p.name, 
    p.gender,
    p.category, 
    p.codeStatus, 
    p.consultant, 
    p.admissionDate,
    p.dischargeDate || 'N/A',
    p.lengthOfStay
  ]);
  exportToPDF("Clinical Patient Record", headers, rows, metadata);
};

export const exportInventoryPDF = (inventory: InventoryItem[], metadata: ReportMetadata) => {
  const headers = ['Item Name', 'Category', 'Stock', 'Min', 'Unit', 'Last Updated'];
  // Fix: Changed i.unit to i.measurementUnit to match updated InventoryItem interface
  const rows = inventory.map(i => [i.name, i.category, i.quantity, i.minThreshold, i.measurementUnit, i.lastUpdated]);
  exportToPDF("Inventory Audit Report", headers, rows, metadata);
};

export const exportEndoscopyPDF = (records: EndoscopyRecord[], metadata: ReportMetadata) => {
  const headers = ['S.No', 'Reg No', 'Patient Name', 'Doctor', 'Procedure', 'Date'];
  const rows = records.map(r => [
    r.serialNo,
    r.regNo,
    r.name,
    r.doctor,
    r.procedure,
    r.date
  ]);
  exportToPDF("Endoscopy Procedure Log", headers, rows, metadata);
};

export const exportIncidentsPDF = (incidents: IncidentRecord[], metadata: ReportMetadata) => {
  const headers = ['Date', 'Patient Name', 'Reg No', 'Category', 'Unit', 'Reported By', 'Description'];
  const rows = incidents.map(i => [
    i.incidentDate,
    i.patientName,
    i.regNo,
    i.category,
    i.unit,
    i.reportedBy,
    i.description ? i.description.replace(/<[^>]*>/g, '') : 'N/A'
  ]);
  exportToPDF("Clinical Incident Report", headers, rows, metadata);
};
