
import React, { useState, useEffect } from 'react';
import Modal from './Modal';

export type ExportFormat = 'PDF' | 'CSV';

interface ExportOptions {
  generatedBy: string;
  includeDateRange: boolean;
  startDate: string;
  endDate: string;
  format: ExportFormat;
}

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  onExport: (options: ExportOptions) => void;
  title: string;
  showDateRange?: boolean;
  defaultGeneratedBy?: string;
}

const ExportModal: React.FC<ExportModalProps> = ({ 
  isOpen, 
  onClose, 
  onExport, 
  title, 
  showDateRange = true,
  defaultGeneratedBy = 'Medical Staff'
}) => {
  const [generatedBy, setGeneratedBy] = useState(defaultGeneratedBy);
  const [includeDateRange, setIncludeDateRange] = useState(false);
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [format, setFormat] = useState<ExportFormat>('PDF');

  useEffect(() => {
    if (isOpen) {
      setGeneratedBy(defaultGeneratedBy);
    }
  }, [isOpen, defaultGeneratedBy]);

  const handleConfirm = () => {
    onExport({
      generatedBy,
      includeDateRange,
      startDate,
      endDate,
      format
    });
    onClose();
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title={title}>
      <div className="space-y-4">
        <div>
          <label className="block text-xs font-bold text-slate-500 uppercase mb-2 tracking-widest">Export Format</label>
          <div className="grid grid-cols-2 gap-2">
            <button
              onClick={() => setFormat('PDF')}
              className={`py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest border transition-all flex items-center justify-center gap-2 ${
                format === 'PDF' ? 'bg-slate-900 text-white border-slate-900 shadow-md' : 'bg-white text-slate-500 border-slate-200 hover:border-slate-300'
              }`}
            >
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"/></svg>
              PDF Document
            </button>
            <button
              onClick={() => setFormat('CSV')}
              className={`py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest border transition-all flex items-center justify-center gap-2 ${
                format === 'CSV' ? 'bg-slate-900 text-white border-slate-900 shadow-md' : 'bg-white text-slate-500 border-slate-200 hover:border-slate-300'
              }`}
            >
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
              CSV Spreadsheet
            </button>
          </div>
        </div>

        <div>
          <label className="block text-xs font-bold text-slate-500 uppercase mb-1 tracking-widest">Generated By</label>
          <input 
            type="text" 
            value={generatedBy}
            onChange={(e) => setGeneratedBy(e.target.value)}
            className="w-full p-2.5 border border-slate-200 rounded-xl focus:ring-2 focus:ring-red-100 outline-none text-[11px] font-bold"
            placeholder="Name of personnel"
          />
        </div>

        {showDateRange && (
          <div className="space-y-3 p-4 bg-slate-50 rounded-xl border border-slate-100">
            <label className="flex items-center space-x-2 cursor-pointer group">
              <input 
                type="checkbox" 
                checked={includeDateRange}
                onChange={(e) => setIncludeDateRange(e.target.checked)}
                className="w-4 h-4 text-red-600 border-slate-300 rounded focus:ring-red-500"
              />
              <span className="text-[10px] font-black text-slate-700 uppercase tracking-widest group-hover:text-red-600 transition-colors">Apply Date Boundary</span>
            </label>

            {includeDateRange && (
              <div className="grid grid-cols-2 gap-3 pt-1 animate-in slide-in-from-top-1 duration-200">
                <div>
                  <label className="block text-[8px] font-black text-slate-400 uppercase mb-1 tracking-widest">Start Date</label>
                  <input 
                    type="date" 
                    value={startDate}
                    onChange={(e) => setStartDate(e.target.value)}
                    className="w-full p-2 text-[10px] font-bold border border-slate-200 rounded-lg outline-none bg-white"
                  />
                </div>
                <div>
                  <label className="block text-[8px] font-black text-slate-400 uppercase mb-1 tracking-widest">End Date</label>
                  <input 
                    type="date" 
                    value={endDate}
                    onChange={(e) => setEndDate(e.target.value)}
                    className="w-full p-2 text-[10px] font-bold border border-slate-200 rounded-lg outline-none bg-white"
                  />
                </div>
              </div>
            )}
          </div>
        )}

        <div className="pt-4 flex gap-3">
          <button 
            onClick={onClose}
            className="flex-1 px-4 py-3 border border-slate-200 text-slate-600 rounded-xl font-black text-[10px] uppercase tracking-widest hover:bg-slate-50 transition-colors"
          >
            Cancel
          </button>
          <button 
            onClick={handleConfirm}
            className="flex-1 bg-red-600 text-white px-4 py-3 rounded-xl font-black text-[10px] uppercase tracking-widest hover:bg-red-700 transition-all shadow-lg flex items-center justify-center space-x-2 shadow-red-100 active:scale-95"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
            <span>Generate {format}</span>
          </button>
        </div>
      </div>
    </Modal>
  );
};

export default ExportModal;
